import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "node:fs";
import path from "node:path";

function loadEnvFileSafe(filePath) {
	if (!fs.existsSync(filePath)) return;
	try {
		if (typeof process.loadEnvFile === "function") {
			process.loadEnvFile(filePath);
			return;
		}
	} catch {}

	try {
		const content = fs.readFileSync(filePath, "utf8");
		for (const line of content.split("\n")) {
			const trimmed = line.trim();
			if (!trimmed || trimmed.startsWith("#")) continue;
			const eqIdx = trimmed.indexOf("=");
			if (eqIdx <= 0) continue;
			const key = trimmed.slice(0, eqIdx).trim();
			let val = trimmed.slice(eqIdx + 1).trim();
			if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
				val = val.slice(1, -1);
			}
			if (key && !(key in process.env)) {
				process.env[key] = val;
			}
		}
	} catch {}
}

loadEnvFileSafe(".env");
loadEnvFileSafe(".env.local");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const qaProduct = (process.argv[2] === "qa-product");

const vaultPath = process.env.OBSIDIAN_VAULT_PATH || process.env.OBSIDIAN_VAULT;
const configDirName = process.env.OBSIDIAN_CONFIG_DIR || ".obsidian";
const pluginName = process.env.PLUGIN_NAME || "kaos";

function copyToVault() {
	if (!vaultPath || !fs.existsSync(vaultPath)) return;
	try {
		const targetDir = path.join(vaultPath, configDirName, "plugins", pluginName);
		fs.mkdirSync(targetDir, { recursive: true });
		for (const file of ["manifest.json", "main.js", "telemetry.js", "styles.css"]) {
			if (fs.existsSync(file)) {
				fs.copyFileSync(file, path.join(targetDir, file));
			}
		}
		console.log(`[vault-sync] Synced plugin files to ${targetDir}`);
	} catch (err) {
		console.warn(`[vault-sync] Failed to sync to vault: ${err.message}`);
	}
}

const vaultSyncPlugin = {
	name: "vault-sync",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				copyToVault();
			}
		});
	},
};

const sharedConfig = {
	banner: { js: banner },
	bundle: true,
	external: [
		"obsidian",
		"electron",
		// Obsidian ships these CM6 packages at runtime.
		// We MUST externalize them to avoid version mismatches.
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: (prod || qaProduct) ? false : "inline",
	treeShaking: true,
	minify: (prod || qaProduct),
	plugins: vaultPath ? [vaultSyncPlugin] : [],
};

// ---------------------------------------------------------------------------
// QA product build — NOT a release artifact.
//
// Built with __KAOS_QA_HARNESS_ENABLED__=true so esbuild keeps the Engine
// control port code. Used for Puppeteer/Obsidian scenario runs only.
// Output: qa/obsidian-harness/product-main.js
//
// Usage:
//   node esbuild.config.mjs qa-product        # one-shot QA product build
//   npm run build:qa-product                   # tsc typecheck + QA product build
// ---------------------------------------------------------------------------
if (qaProduct) {
	const qaProductContext = await esbuild.context({
		...sharedConfig,
		entryPoints: ["src/main.ts"],
		outfile: "qa/obsidian-harness/product-main.js",
		define: {
			// true → esbuild KEEPS the EngineControlPort block for harness use
			"__KAOS_QA_HARNESS_ENABLED__": "true",
		},
	});
	await qaProductContext.rebuild();
	process.exit(0);
}

// ---------------------------------------------------------------------------
// Product bundle — shipped to users. Must not contain Engine control capabilities.
// __KAOS_QA_HARNESS_ENABLED__=false → esbuild dead-code-eliminates the port.
// ---------------------------------------------------------------------------
const mainContext = await esbuild.context({
	...sharedConfig,
	entryPoints: ["src/main.ts"],
	outfile: "main.js",
	define: {
		// false → esbuild eliminates getEngineControlPort, ingestDiskFileNow, etc.
		"__KAOS_QA_HARNESS_ENABLED__": "false",
	},
});

// Telemetry/Observer bundle — FlightRecorder, DeviceWitnessTracker, DiagnosticsService
// Loaded dynamically by main.ts only when settings.debug or settings.qaDebugMode.
// Must NOT contain VFS torture, scenario steppers, unsafe CRDT/sync, network holds,
// or any mutation harness code. Mutation harness (Puppeteer) lives in qa/.
const telemetryContext = await esbuild.context({
	...sharedConfig,
	entryPoints: ["src/telemetry/installTelemetryRuntime.ts"],
	outfile: "telemetry.js",
});

if (prod) {
	await Promise.all([
		mainContext.rebuild(),
		telemetryContext.rebuild(),
	]);
	process.exit(0);
} else {
	if (vaultPath) {
		console.log(`[vault-sync] Auto-sync active for vault: ${vaultPath}`);
	}
	await Promise.all([
		mainContext.watch(),
		telemetryContext.watch(),
	]);
}
